/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-02-27 at 04:01:29 UTC 
 * Modify at your own risk.
 */

package com.appsack.model.appideavoteendpoint;

/**
 * Service definition for Appideavoteendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AppideavoteendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Appideavoteendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the appideavoteendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://amiable-reducer-470.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "appideavoteendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Appideavoteendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Appideavoteendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAppIdeaVote".
   *
   * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
   * any optional parameters, call the {@link GetAppIdeaVote#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetAppIdeaVote getAppIdeaVote(java.lang.Long id) throws java.io.IOException {
    GetAppIdeaVote result = new GetAppIdeaVote(id);
    initialize(result);
    return result;
  }

  public class GetAppIdeaVote extends AppideavoteendpointRequest<com.appsack.model.appideavoteendpoint.model.AppIdeaVote> {

    private static final String REST_PATH = "appideavote/{id}";

    /**
     * Create a request for the method "getAppIdeaVote".
     *
     * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
     * any optional parameters, call the {@link GetAppIdeaVote#execute()} method to invoke the remote
     * operation. <p> {@link GetAppIdeaVote#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAppIdeaVote(java.lang.Long id) {
      super(Appideavoteendpoint.this, "GET", REST_PATH, null, com.appsack.model.appideavoteendpoint.model.AppIdeaVote.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAppIdeaVote setAlt(java.lang.String alt) {
      return (GetAppIdeaVote) super.setAlt(alt);
    }

    @Override
    public GetAppIdeaVote setFields(java.lang.String fields) {
      return (GetAppIdeaVote) super.setFields(fields);
    }

    @Override
    public GetAppIdeaVote setKey(java.lang.String key) {
      return (GetAppIdeaVote) super.setKey(key);
    }

    @Override
    public GetAppIdeaVote setOauthToken(java.lang.String oauthToken) {
      return (GetAppIdeaVote) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAppIdeaVote setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAppIdeaVote) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAppIdeaVote setQuotaUser(java.lang.String quotaUser) {
      return (GetAppIdeaVote) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAppIdeaVote setUserIp(java.lang.String userIp) {
      return (GetAppIdeaVote) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetAppIdeaVote setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAppIdeaVote set(String parameterName, Object value) {
      return (GetAppIdeaVote) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getVotesByAppIdea".
   *
   * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
   * any optional parameters, call the {@link GetVotesByAppIdea#execute()} method to invoke the remote
   * operation.
   *
   * @param appIdeaId
   * @param vote
   * @return the request
   */
  public GetVotesByAppIdea getVotesByAppIdea(java.lang.Long appIdeaId, java.lang.Integer vote) throws java.io.IOException {
    GetVotesByAppIdea result = new GetVotesByAppIdea(appIdeaId, vote);
    initialize(result);
    return result;
  }

  public class GetVotesByAppIdea extends AppideavoteendpointRequest<com.appsack.model.appideavoteendpoint.model.AppIdeaVoteCollection> {

    private static final String REST_PATH = "appideavotecollection/{appIdeaId}/{vote}";

    /**
     * Create a request for the method "getVotesByAppIdea".
     *
     * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
     * any optional parameters, call the {@link GetVotesByAppIdea#execute()} method to invoke the
     * remote operation. <p> {@link GetVotesByAppIdea#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param appIdeaId
     * @param vote
     * @since 1.13
     */
    protected GetVotesByAppIdea(java.lang.Long appIdeaId, java.lang.Integer vote) {
      super(Appideavoteendpoint.this, "GET", REST_PATH, null, com.appsack.model.appideavoteendpoint.model.AppIdeaVoteCollection.class);
      this.appIdeaId = com.google.api.client.util.Preconditions.checkNotNull(appIdeaId, "Required parameter appIdeaId must be specified.");
      this.vote = com.google.api.client.util.Preconditions.checkNotNull(vote, "Required parameter vote must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetVotesByAppIdea setAlt(java.lang.String alt) {
      return (GetVotesByAppIdea) super.setAlt(alt);
    }

    @Override
    public GetVotesByAppIdea setFields(java.lang.String fields) {
      return (GetVotesByAppIdea) super.setFields(fields);
    }

    @Override
    public GetVotesByAppIdea setKey(java.lang.String key) {
      return (GetVotesByAppIdea) super.setKey(key);
    }

    @Override
    public GetVotesByAppIdea setOauthToken(java.lang.String oauthToken) {
      return (GetVotesByAppIdea) super.setOauthToken(oauthToken);
    }

    @Override
    public GetVotesByAppIdea setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetVotesByAppIdea) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetVotesByAppIdea setQuotaUser(java.lang.String quotaUser) {
      return (GetVotesByAppIdea) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetVotesByAppIdea setUserIp(java.lang.String userIp) {
      return (GetVotesByAppIdea) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long appIdeaId;

    /**

     */
    public java.lang.Long getAppIdeaId() {
      return appIdeaId;
    }

    public GetVotesByAppIdea setAppIdeaId(java.lang.Long appIdeaId) {
      this.appIdeaId = appIdeaId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer vote;

    /**

     */
    public java.lang.Integer getVote() {
      return vote;
    }

    public GetVotesByAppIdea setVote(java.lang.Integer vote) {
      this.vote = vote;
      return this;
    }

    @Override
    public GetVotesByAppIdea set(String parameterName, Object value) {
      return (GetVotesByAppIdea) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertAppIdeaVote".
   *
   * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
   * any optional parameters, call the {@link InsertAppIdeaVote#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appsack.model.appideavoteendpoint.model.AppIdeaVote}
   * @return the request
   */
  public InsertAppIdeaVote insertAppIdeaVote(com.appsack.model.appideavoteendpoint.model.AppIdeaVote content) throws java.io.IOException {
    InsertAppIdeaVote result = new InsertAppIdeaVote(content);
    initialize(result);
    return result;
  }

  public class InsertAppIdeaVote extends AppideavoteendpointRequest<com.appsack.model.appideavoteendpoint.model.AppIdeaVote> {

    private static final String REST_PATH = "appideavote";

    /**
     * Create a request for the method "insertAppIdeaVote".
     *
     * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
     * any optional parameters, call the {@link InsertAppIdeaVote#execute()} method to invoke the
     * remote operation. <p> {@link InsertAppIdeaVote#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.appsack.model.appideavoteendpoint.model.AppIdeaVote}
     * @since 1.13
     */
    protected InsertAppIdeaVote(com.appsack.model.appideavoteendpoint.model.AppIdeaVote content) {
      super(Appideavoteendpoint.this, "POST", REST_PATH, content, com.appsack.model.appideavoteendpoint.model.AppIdeaVote.class);
    }

    @Override
    public InsertAppIdeaVote setAlt(java.lang.String alt) {
      return (InsertAppIdeaVote) super.setAlt(alt);
    }

    @Override
    public InsertAppIdeaVote setFields(java.lang.String fields) {
      return (InsertAppIdeaVote) super.setFields(fields);
    }

    @Override
    public InsertAppIdeaVote setKey(java.lang.String key) {
      return (InsertAppIdeaVote) super.setKey(key);
    }

    @Override
    public InsertAppIdeaVote setOauthToken(java.lang.String oauthToken) {
      return (InsertAppIdeaVote) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertAppIdeaVote setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertAppIdeaVote) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertAppIdeaVote setQuotaUser(java.lang.String quotaUser) {
      return (InsertAppIdeaVote) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertAppIdeaVote setUserIp(java.lang.String userIp) {
      return (InsertAppIdeaVote) super.setUserIp(userIp);
    }

    @Override
    public InsertAppIdeaVote set(String parameterName, Object value) {
      return (InsertAppIdeaVote) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAppIdeaVote".
   *
   * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
   * any optional parameters, call the {@link ListAppIdeaVote#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListAppIdeaVote listAppIdeaVote() throws java.io.IOException {
    ListAppIdeaVote result = new ListAppIdeaVote();
    initialize(result);
    return result;
  }

  public class ListAppIdeaVote extends AppideavoteendpointRequest<com.appsack.model.appideavoteendpoint.model.CollectionResponseAppIdeaVote> {

    private static final String REST_PATH = "appideavote";

    /**
     * Create a request for the method "listAppIdeaVote".
     *
     * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
     * any optional parameters, call the {@link ListAppIdeaVote#execute()} method to invoke the remote
     * operation. <p> {@link ListAppIdeaVote#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAppIdeaVote() {
      super(Appideavoteendpoint.this, "GET", REST_PATH, null, com.appsack.model.appideavoteendpoint.model.CollectionResponseAppIdeaVote.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAppIdeaVote setAlt(java.lang.String alt) {
      return (ListAppIdeaVote) super.setAlt(alt);
    }

    @Override
    public ListAppIdeaVote setFields(java.lang.String fields) {
      return (ListAppIdeaVote) super.setFields(fields);
    }

    @Override
    public ListAppIdeaVote setKey(java.lang.String key) {
      return (ListAppIdeaVote) super.setKey(key);
    }

    @Override
    public ListAppIdeaVote setOauthToken(java.lang.String oauthToken) {
      return (ListAppIdeaVote) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAppIdeaVote setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAppIdeaVote) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAppIdeaVote setQuotaUser(java.lang.String quotaUser) {
      return (ListAppIdeaVote) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAppIdeaVote setUserIp(java.lang.String userIp) {
      return (ListAppIdeaVote) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAppIdeaVote setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListAppIdeaVote setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListAppIdeaVote set(String parameterName, Object value) {
      return (ListAppIdeaVote) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAppIdeaVote".
   *
   * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
   * any optional parameters, call the {@link RemoveAppIdeaVote#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveAppIdeaVote removeAppIdeaVote(java.lang.Long id) throws java.io.IOException {
    RemoveAppIdeaVote result = new RemoveAppIdeaVote(id);
    initialize(result);
    return result;
  }

  public class RemoveAppIdeaVote extends AppideavoteendpointRequest<Void> {

    private static final String REST_PATH = "appideavote/{id}";

    /**
     * Create a request for the method "removeAppIdeaVote".
     *
     * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
     * any optional parameters, call the {@link RemoveAppIdeaVote#execute()} method to invoke the
     * remote operation. <p> {@link RemoveAppIdeaVote#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveAppIdeaVote(java.lang.Long id) {
      super(Appideavoteendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveAppIdeaVote setAlt(java.lang.String alt) {
      return (RemoveAppIdeaVote) super.setAlt(alt);
    }

    @Override
    public RemoveAppIdeaVote setFields(java.lang.String fields) {
      return (RemoveAppIdeaVote) super.setFields(fields);
    }

    @Override
    public RemoveAppIdeaVote setKey(java.lang.String key) {
      return (RemoveAppIdeaVote) super.setKey(key);
    }

    @Override
    public RemoveAppIdeaVote setOauthToken(java.lang.String oauthToken) {
      return (RemoveAppIdeaVote) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAppIdeaVote setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAppIdeaVote) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAppIdeaVote setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAppIdeaVote) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAppIdeaVote setUserIp(java.lang.String userIp) {
      return (RemoveAppIdeaVote) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveAppIdeaVote setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveAppIdeaVote set(String parameterName, Object value) {
      return (RemoveAppIdeaVote) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateAppIdeaVote".
   *
   * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
   * any optional parameters, call the {@link UpdateAppIdeaVote#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appsack.model.appideavoteendpoint.model.AppIdeaVote}
   * @return the request
   */
  public UpdateAppIdeaVote updateAppIdeaVote(com.appsack.model.appideavoteendpoint.model.AppIdeaVote content) throws java.io.IOException {
    UpdateAppIdeaVote result = new UpdateAppIdeaVote(content);
    initialize(result);
    return result;
  }

  public class UpdateAppIdeaVote extends AppideavoteendpointRequest<com.appsack.model.appideavoteendpoint.model.AppIdeaVote> {

    private static final String REST_PATH = "appideavote";

    /**
     * Create a request for the method "updateAppIdeaVote".
     *
     * This request holds the parameters needed by the the appideavoteendpoint server.  After setting
     * any optional parameters, call the {@link UpdateAppIdeaVote#execute()} method to invoke the
     * remote operation. <p> {@link UpdateAppIdeaVote#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.appsack.model.appideavoteendpoint.model.AppIdeaVote}
     * @since 1.13
     */
    protected UpdateAppIdeaVote(com.appsack.model.appideavoteendpoint.model.AppIdeaVote content) {
      super(Appideavoteendpoint.this, "PUT", REST_PATH, content, com.appsack.model.appideavoteendpoint.model.AppIdeaVote.class);
    }

    @Override
    public UpdateAppIdeaVote setAlt(java.lang.String alt) {
      return (UpdateAppIdeaVote) super.setAlt(alt);
    }

    @Override
    public UpdateAppIdeaVote setFields(java.lang.String fields) {
      return (UpdateAppIdeaVote) super.setFields(fields);
    }

    @Override
    public UpdateAppIdeaVote setKey(java.lang.String key) {
      return (UpdateAppIdeaVote) super.setKey(key);
    }

    @Override
    public UpdateAppIdeaVote setOauthToken(java.lang.String oauthToken) {
      return (UpdateAppIdeaVote) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateAppIdeaVote setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateAppIdeaVote) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateAppIdeaVote setQuotaUser(java.lang.String quotaUser) {
      return (UpdateAppIdeaVote) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateAppIdeaVote setUserIp(java.lang.String userIp) {
      return (UpdateAppIdeaVote) super.setUserIp(userIp);
    }

    @Override
    public UpdateAppIdeaVote set(String parameterName, Object value) {
      return (UpdateAppIdeaVote) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Appideavoteendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Appideavoteendpoint}. */
    @Override
    public Appideavoteendpoint build() {
      return new Appideavoteendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AppideavoteendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAppideavoteendpointRequestInitializer(
        AppideavoteendpointRequestInitializer appideavoteendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(appideavoteendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
