/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-02-27 at 04:02:03 UTC 
 * Modify at your own risk.
 */

package com.appsack.model.userchangelogendpoint;

/**
 * Service definition for Userchangelogendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UserchangelogendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Userchangelogendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the userchangelogendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://amiable-reducer-470.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "userchangelogendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Userchangelogendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Userchangelogendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getUserChangeLog".
   *
   * This request holds the parameters needed by the the userchangelogendpoint server.  After setting
   * any optional parameters, call the {@link GetUserChangeLog#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetUserChangeLog getUserChangeLog(java.lang.Long id) throws java.io.IOException {
    GetUserChangeLog result = new GetUserChangeLog(id);
    initialize(result);
    return result;
  }

  public class GetUserChangeLog extends UserchangelogendpointRequest<com.appsack.model.userchangelogendpoint.model.UserChangeLog> {

    private static final String REST_PATH = "userchangelog/{id}";

    /**
     * Create a request for the method "getUserChangeLog".
     *
     * This request holds the parameters needed by the the userchangelogendpoint server.  After
     * setting any optional parameters, call the {@link GetUserChangeLog#execute()} method to invoke
     * the remote operation. <p> {@link GetUserChangeLog#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetUserChangeLog(java.lang.Long id) {
      super(Userchangelogendpoint.this, "GET", REST_PATH, null, com.appsack.model.userchangelogendpoint.model.UserChangeLog.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetUserChangeLog setAlt(java.lang.String alt) {
      return (GetUserChangeLog) super.setAlt(alt);
    }

    @Override
    public GetUserChangeLog setFields(java.lang.String fields) {
      return (GetUserChangeLog) super.setFields(fields);
    }

    @Override
    public GetUserChangeLog setKey(java.lang.String key) {
      return (GetUserChangeLog) super.setKey(key);
    }

    @Override
    public GetUserChangeLog setOauthToken(java.lang.String oauthToken) {
      return (GetUserChangeLog) super.setOauthToken(oauthToken);
    }

    @Override
    public GetUserChangeLog setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetUserChangeLog) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetUserChangeLog setQuotaUser(java.lang.String quotaUser) {
      return (GetUserChangeLog) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetUserChangeLog setUserIp(java.lang.String userIp) {
      return (GetUserChangeLog) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetUserChangeLog setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetUserChangeLog set(String parameterName, Object value) {
      return (GetUserChangeLog) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertUserChangeLog".
   *
   * This request holds the parameters needed by the the userchangelogendpoint server.  After setting
   * any optional parameters, call the {@link InsertUserChangeLog#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.appsack.model.userchangelogendpoint.model.UserChangeLog}
   * @return the request
   */
  public InsertUserChangeLog insertUserChangeLog(com.appsack.model.userchangelogendpoint.model.UserChangeLog content) throws java.io.IOException {
    InsertUserChangeLog result = new InsertUserChangeLog(content);
    initialize(result);
    return result;
  }

  public class InsertUserChangeLog extends UserchangelogendpointRequest<com.appsack.model.userchangelogendpoint.model.UserChangeLog> {

    private static final String REST_PATH = "userchangelog";

    /**
     * Create a request for the method "insertUserChangeLog".
     *
     * This request holds the parameters needed by the the userchangelogendpoint server.  After
     * setting any optional parameters, call the {@link InsertUserChangeLog#execute()} method to
     * invoke the remote operation. <p> {@link InsertUserChangeLog#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appsack.model.userchangelogendpoint.model.UserChangeLog}
     * @since 1.13
     */
    protected InsertUserChangeLog(com.appsack.model.userchangelogendpoint.model.UserChangeLog content) {
      super(Userchangelogendpoint.this, "POST", REST_PATH, content, com.appsack.model.userchangelogendpoint.model.UserChangeLog.class);
    }

    @Override
    public InsertUserChangeLog setAlt(java.lang.String alt) {
      return (InsertUserChangeLog) super.setAlt(alt);
    }

    @Override
    public InsertUserChangeLog setFields(java.lang.String fields) {
      return (InsertUserChangeLog) super.setFields(fields);
    }

    @Override
    public InsertUserChangeLog setKey(java.lang.String key) {
      return (InsertUserChangeLog) super.setKey(key);
    }

    @Override
    public InsertUserChangeLog setOauthToken(java.lang.String oauthToken) {
      return (InsertUserChangeLog) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertUserChangeLog setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertUserChangeLog) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertUserChangeLog setQuotaUser(java.lang.String quotaUser) {
      return (InsertUserChangeLog) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertUserChangeLog setUserIp(java.lang.String userIp) {
      return (InsertUserChangeLog) super.setUserIp(userIp);
    }

    @Override
    public InsertUserChangeLog set(String parameterName, Object value) {
      return (InsertUserChangeLog) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listUserChangeLog".
   *
   * This request holds the parameters needed by the the userchangelogendpoint server.  After setting
   * any optional parameters, call the {@link ListUserChangeLog#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListUserChangeLog listUserChangeLog() throws java.io.IOException {
    ListUserChangeLog result = new ListUserChangeLog();
    initialize(result);
    return result;
  }

  public class ListUserChangeLog extends UserchangelogendpointRequest<com.appsack.model.userchangelogendpoint.model.CollectionResponseUserChangeLog> {

    private static final String REST_PATH = "userchangelog";

    /**
     * Create a request for the method "listUserChangeLog".
     *
     * This request holds the parameters needed by the the userchangelogendpoint server.  After
     * setting any optional parameters, call the {@link ListUserChangeLog#execute()} method to invoke
     * the remote operation. <p> {@link ListUserChangeLog#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListUserChangeLog() {
      super(Userchangelogendpoint.this, "GET", REST_PATH, null, com.appsack.model.userchangelogendpoint.model.CollectionResponseUserChangeLog.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListUserChangeLog setAlt(java.lang.String alt) {
      return (ListUserChangeLog) super.setAlt(alt);
    }

    @Override
    public ListUserChangeLog setFields(java.lang.String fields) {
      return (ListUserChangeLog) super.setFields(fields);
    }

    @Override
    public ListUserChangeLog setKey(java.lang.String key) {
      return (ListUserChangeLog) super.setKey(key);
    }

    @Override
    public ListUserChangeLog setOauthToken(java.lang.String oauthToken) {
      return (ListUserChangeLog) super.setOauthToken(oauthToken);
    }

    @Override
    public ListUserChangeLog setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListUserChangeLog) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListUserChangeLog setQuotaUser(java.lang.String quotaUser) {
      return (ListUserChangeLog) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListUserChangeLog setUserIp(java.lang.String userIp) {
      return (ListUserChangeLog) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListUserChangeLog setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListUserChangeLog setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListUserChangeLog set(String parameterName, Object value) {
      return (ListUserChangeLog) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeUserChangeLog".
   *
   * This request holds the parameters needed by the the userchangelogendpoint server.  After setting
   * any optional parameters, call the {@link RemoveUserChangeLog#execute()} method to invoke the
   * remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveUserChangeLog removeUserChangeLog(java.lang.Long id) throws java.io.IOException {
    RemoveUserChangeLog result = new RemoveUserChangeLog(id);
    initialize(result);
    return result;
  }

  public class RemoveUserChangeLog extends UserchangelogendpointRequest<Void> {

    private static final String REST_PATH = "userchangelog/{id}";

    /**
     * Create a request for the method "removeUserChangeLog".
     *
     * This request holds the parameters needed by the the userchangelogendpoint server.  After
     * setting any optional parameters, call the {@link RemoveUserChangeLog#execute()} method to
     * invoke the remote operation. <p> {@link RemoveUserChangeLog#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveUserChangeLog(java.lang.Long id) {
      super(Userchangelogendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveUserChangeLog setAlt(java.lang.String alt) {
      return (RemoveUserChangeLog) super.setAlt(alt);
    }

    @Override
    public RemoveUserChangeLog setFields(java.lang.String fields) {
      return (RemoveUserChangeLog) super.setFields(fields);
    }

    @Override
    public RemoveUserChangeLog setKey(java.lang.String key) {
      return (RemoveUserChangeLog) super.setKey(key);
    }

    @Override
    public RemoveUserChangeLog setOauthToken(java.lang.String oauthToken) {
      return (RemoveUserChangeLog) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveUserChangeLog setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveUserChangeLog) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveUserChangeLog setQuotaUser(java.lang.String quotaUser) {
      return (RemoveUserChangeLog) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveUserChangeLog setUserIp(java.lang.String userIp) {
      return (RemoveUserChangeLog) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveUserChangeLog setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveUserChangeLog set(String parameterName, Object value) {
      return (RemoveUserChangeLog) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateUserChangeLog".
   *
   * This request holds the parameters needed by the the userchangelogendpoint server.  After setting
   * any optional parameters, call the {@link UpdateUserChangeLog#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.appsack.model.userchangelogendpoint.model.UserChangeLog}
   * @return the request
   */
  public UpdateUserChangeLog updateUserChangeLog(com.appsack.model.userchangelogendpoint.model.UserChangeLog content) throws java.io.IOException {
    UpdateUserChangeLog result = new UpdateUserChangeLog(content);
    initialize(result);
    return result;
  }

  public class UpdateUserChangeLog extends UserchangelogendpointRequest<com.appsack.model.userchangelogendpoint.model.UserChangeLog> {

    private static final String REST_PATH = "userchangelog";

    /**
     * Create a request for the method "updateUserChangeLog".
     *
     * This request holds the parameters needed by the the userchangelogendpoint server.  After
     * setting any optional parameters, call the {@link UpdateUserChangeLog#execute()} method to
     * invoke the remote operation. <p> {@link UpdateUserChangeLog#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.appsack.model.userchangelogendpoint.model.UserChangeLog}
     * @since 1.13
     */
    protected UpdateUserChangeLog(com.appsack.model.userchangelogendpoint.model.UserChangeLog content) {
      super(Userchangelogendpoint.this, "PUT", REST_PATH, content, com.appsack.model.userchangelogendpoint.model.UserChangeLog.class);
    }

    @Override
    public UpdateUserChangeLog setAlt(java.lang.String alt) {
      return (UpdateUserChangeLog) super.setAlt(alt);
    }

    @Override
    public UpdateUserChangeLog setFields(java.lang.String fields) {
      return (UpdateUserChangeLog) super.setFields(fields);
    }

    @Override
    public UpdateUserChangeLog setKey(java.lang.String key) {
      return (UpdateUserChangeLog) super.setKey(key);
    }

    @Override
    public UpdateUserChangeLog setOauthToken(java.lang.String oauthToken) {
      return (UpdateUserChangeLog) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateUserChangeLog setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateUserChangeLog) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateUserChangeLog setQuotaUser(java.lang.String quotaUser) {
      return (UpdateUserChangeLog) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateUserChangeLog setUserIp(java.lang.String userIp) {
      return (UpdateUserChangeLog) super.setUserIp(userIp);
    }

    @Override
    public UpdateUserChangeLog set(String parameterName, Object value) {
      return (UpdateUserChangeLog) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Userchangelogendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Userchangelogendpoint}. */
    @Override
    public Userchangelogendpoint build() {
      return new Userchangelogendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UserchangelogendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUserchangelogendpointRequestInitializer(
        UserchangelogendpointRequestInitializer userchangelogendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(userchangelogendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
