/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-02-27 at 04:01:33 UTC 
 * Modify at your own risk.
 */

package com.appsack.model.appideaendpoint;

/**
 * Service definition for Appideaendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AppideaendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Appideaendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the appideaendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://amiable-reducer-470.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "appideaendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Appideaendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Appideaendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAppIdea".
   *
   * This request holds the parameters needed by the the appideaendpoint server.  After setting any
   * optional parameters, call the {@link GetAppIdea#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetAppIdea getAppIdea(java.lang.Long id) throws java.io.IOException {
    GetAppIdea result = new GetAppIdea(id);
    initialize(result);
    return result;
  }

  public class GetAppIdea extends AppideaendpointRequest<com.appsack.model.appideaendpoint.model.AppIdea> {

    private static final String REST_PATH = "appidea/{id}";

    /**
     * Create a request for the method "getAppIdea".
     *
     * This request holds the parameters needed by the the appideaendpoint server.  After setting any
     * optional parameters, call the {@link GetAppIdea#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetAppIdea#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAppIdea(java.lang.Long id) {
      super(Appideaendpoint.this, "GET", REST_PATH, null, com.appsack.model.appideaendpoint.model.AppIdea.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAppIdea setAlt(java.lang.String alt) {
      return (GetAppIdea) super.setAlt(alt);
    }

    @Override
    public GetAppIdea setFields(java.lang.String fields) {
      return (GetAppIdea) super.setFields(fields);
    }

    @Override
    public GetAppIdea setKey(java.lang.String key) {
      return (GetAppIdea) super.setKey(key);
    }

    @Override
    public GetAppIdea setOauthToken(java.lang.String oauthToken) {
      return (GetAppIdea) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAppIdea setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAppIdea) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAppIdea setQuotaUser(java.lang.String quotaUser) {
      return (GetAppIdea) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAppIdea setUserIp(java.lang.String userIp) {
      return (GetAppIdea) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetAppIdea setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAppIdea set(String parameterName, Object value) {
      return (GetAppIdea) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertAppIdea".
   *
   * This request holds the parameters needed by the the appideaendpoint server.  After setting any
   * optional parameters, call the {@link InsertAppIdea#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appsack.model.appideaendpoint.model.AppIdea}
   * @return the request
   */
  public InsertAppIdea insertAppIdea(com.appsack.model.appideaendpoint.model.AppIdea content) throws java.io.IOException {
    InsertAppIdea result = new InsertAppIdea(content);
    initialize(result);
    return result;
  }

  public class InsertAppIdea extends AppideaendpointRequest<com.appsack.model.appideaendpoint.model.AppIdea> {

    private static final String REST_PATH = "appidea";

    /**
     * Create a request for the method "insertAppIdea".
     *
     * This request holds the parameters needed by the the appideaendpoint server.  After setting any
     * optional parameters, call the {@link InsertAppIdea#execute()} method to invoke the remote
     * operation. <p> {@link InsertAppIdea#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.appsack.model.appideaendpoint.model.AppIdea}
     * @since 1.13
     */
    protected InsertAppIdea(com.appsack.model.appideaendpoint.model.AppIdea content) {
      super(Appideaendpoint.this, "POST", REST_PATH, content, com.appsack.model.appideaendpoint.model.AppIdea.class);
    }

    @Override
    public InsertAppIdea setAlt(java.lang.String alt) {
      return (InsertAppIdea) super.setAlt(alt);
    }

    @Override
    public InsertAppIdea setFields(java.lang.String fields) {
      return (InsertAppIdea) super.setFields(fields);
    }

    @Override
    public InsertAppIdea setKey(java.lang.String key) {
      return (InsertAppIdea) super.setKey(key);
    }

    @Override
    public InsertAppIdea setOauthToken(java.lang.String oauthToken) {
      return (InsertAppIdea) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertAppIdea setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertAppIdea) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertAppIdea setQuotaUser(java.lang.String quotaUser) {
      return (InsertAppIdea) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertAppIdea setUserIp(java.lang.String userIp) {
      return (InsertAppIdea) super.setUserIp(userIp);
    }

    @Override
    public InsertAppIdea set(String parameterName, Object value) {
      return (InsertAppIdea) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAppIdea".
   *
   * This request holds the parameters needed by the the appideaendpoint server.  After setting any
   * optional parameters, call the {@link ListAppIdea#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListAppIdea listAppIdea() throws java.io.IOException {
    ListAppIdea result = new ListAppIdea();
    initialize(result);
    return result;
  }

  public class ListAppIdea extends AppideaendpointRequest<com.appsack.model.appideaendpoint.model.CollectionResponseAppIdea> {

    private static final String REST_PATH = "appidea";

    /**
     * Create a request for the method "listAppIdea".
     *
     * This request holds the parameters needed by the the appideaendpoint server.  After setting any
     * optional parameters, call the {@link ListAppIdea#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListAppIdea#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAppIdea() {
      super(Appideaendpoint.this, "GET", REST_PATH, null, com.appsack.model.appideaendpoint.model.CollectionResponseAppIdea.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAppIdea setAlt(java.lang.String alt) {
      return (ListAppIdea) super.setAlt(alt);
    }

    @Override
    public ListAppIdea setFields(java.lang.String fields) {
      return (ListAppIdea) super.setFields(fields);
    }

    @Override
    public ListAppIdea setKey(java.lang.String key) {
      return (ListAppIdea) super.setKey(key);
    }

    @Override
    public ListAppIdea setOauthToken(java.lang.String oauthToken) {
      return (ListAppIdea) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAppIdea setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAppIdea) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAppIdea setQuotaUser(java.lang.String quotaUser) {
      return (ListAppIdea) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAppIdea setUserIp(java.lang.String userIp) {
      return (ListAppIdea) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAppIdea setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListAppIdea setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListAppIdea set(String parameterName, Object value) {
      return (ListAppIdea) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAppIdeasByUserId".
   *
   * This request holds the parameters needed by the the appideaendpoint server.  After setting any
   * optional parameters, call the {@link ListAppIdeasByUserId#execute()} method to invoke the remote
   * operation.
   *
   * @param userId
   * @param vote
   * @return the request
   */
  public ListAppIdeasByUserId listAppIdeasByUserId(java.lang.Long userId, java.lang.Integer vote) throws java.io.IOException {
    ListAppIdeasByUserId result = new ListAppIdeasByUserId(userId, vote);
    initialize(result);
    return result;
  }

  public class ListAppIdeasByUserId extends AppideaendpointRequest<com.appsack.model.appideaendpoint.model.CollectionResponseAppIdea> {

    private static final String REST_PATH = "appidea/{userId}/{vote}";

    /**
     * Create a request for the method "listAppIdeasByUserId".
     *
     * This request holds the parameters needed by the the appideaendpoint server.  After setting any
     * optional parameters, call the {@link ListAppIdeasByUserId#execute()} method to invoke the
     * remote operation. <p> {@link ListAppIdeasByUserId#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param userId
     * @param vote
     * @since 1.13
     */
    protected ListAppIdeasByUserId(java.lang.Long userId, java.lang.Integer vote) {
      super(Appideaendpoint.this, "GET", REST_PATH, null, com.appsack.model.appideaendpoint.model.CollectionResponseAppIdea.class);
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
      this.vote = com.google.api.client.util.Preconditions.checkNotNull(vote, "Required parameter vote must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAppIdeasByUserId setAlt(java.lang.String alt) {
      return (ListAppIdeasByUserId) super.setAlt(alt);
    }

    @Override
    public ListAppIdeasByUserId setFields(java.lang.String fields) {
      return (ListAppIdeasByUserId) super.setFields(fields);
    }

    @Override
    public ListAppIdeasByUserId setKey(java.lang.String key) {
      return (ListAppIdeasByUserId) super.setKey(key);
    }

    @Override
    public ListAppIdeasByUserId setOauthToken(java.lang.String oauthToken) {
      return (ListAppIdeasByUserId) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAppIdeasByUserId setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAppIdeasByUserId) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAppIdeasByUserId setQuotaUser(java.lang.String quotaUser) {
      return (ListAppIdeasByUserId) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAppIdeasByUserId setUserIp(java.lang.String userIp) {
      return (ListAppIdeasByUserId) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long userId;

    /**

     */
    public java.lang.Long getUserId() {
      return userId;
    }

    public ListAppIdeasByUserId setUserId(java.lang.Long userId) {
      this.userId = userId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer vote;

    /**

     */
    public java.lang.Integer getVote() {
      return vote;
    }

    public ListAppIdeasByUserId setVote(java.lang.Integer vote) {
      this.vote = vote;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAppIdeasByUserId setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListAppIdeasByUserId setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListAppIdeasByUserId set(String parameterName, Object value) {
      return (ListAppIdeasByUserId) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAppIdea".
   *
   * This request holds the parameters needed by the the appideaendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAppIdea#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveAppIdea removeAppIdea(java.lang.Long id) throws java.io.IOException {
    RemoveAppIdea result = new RemoveAppIdea(id);
    initialize(result);
    return result;
  }

  public class RemoveAppIdea extends AppideaendpointRequest<Void> {

    private static final String REST_PATH = "appidea/{id}";

    /**
     * Create a request for the method "removeAppIdea".
     *
     * This request holds the parameters needed by the the appideaendpoint server.  After setting any
     * optional parameters, call the {@link RemoveAppIdea#execute()} method to invoke the remote
     * operation. <p> {@link RemoveAppIdea#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveAppIdea(java.lang.Long id) {
      super(Appideaendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveAppIdea setAlt(java.lang.String alt) {
      return (RemoveAppIdea) super.setAlt(alt);
    }

    @Override
    public RemoveAppIdea setFields(java.lang.String fields) {
      return (RemoveAppIdea) super.setFields(fields);
    }

    @Override
    public RemoveAppIdea setKey(java.lang.String key) {
      return (RemoveAppIdea) super.setKey(key);
    }

    @Override
    public RemoveAppIdea setOauthToken(java.lang.String oauthToken) {
      return (RemoveAppIdea) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAppIdea setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAppIdea) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAppIdea setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAppIdea) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAppIdea setUserIp(java.lang.String userIp) {
      return (RemoveAppIdea) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveAppIdea setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveAppIdea set(String parameterName, Object value) {
      return (RemoveAppIdea) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateAppIdea".
   *
   * This request holds the parameters needed by the the appideaendpoint server.  After setting any
   * optional parameters, call the {@link UpdateAppIdea#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.appsack.model.appideaendpoint.model.AppIdea}
   * @return the request
   */
  public UpdateAppIdea updateAppIdea(com.appsack.model.appideaendpoint.model.AppIdea content) throws java.io.IOException {
    UpdateAppIdea result = new UpdateAppIdea(content);
    initialize(result);
    return result;
  }

  public class UpdateAppIdea extends AppideaendpointRequest<com.appsack.model.appideaendpoint.model.AppIdea> {

    private static final String REST_PATH = "appidea";

    /**
     * Create a request for the method "updateAppIdea".
     *
     * This request holds the parameters needed by the the appideaendpoint server.  After setting any
     * optional parameters, call the {@link UpdateAppIdea#execute()} method to invoke the remote
     * operation. <p> {@link UpdateAppIdea#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.appsack.model.appideaendpoint.model.AppIdea}
     * @since 1.13
     */
    protected UpdateAppIdea(com.appsack.model.appideaendpoint.model.AppIdea content) {
      super(Appideaendpoint.this, "PUT", REST_PATH, content, com.appsack.model.appideaendpoint.model.AppIdea.class);
    }

    @Override
    public UpdateAppIdea setAlt(java.lang.String alt) {
      return (UpdateAppIdea) super.setAlt(alt);
    }

    @Override
    public UpdateAppIdea setFields(java.lang.String fields) {
      return (UpdateAppIdea) super.setFields(fields);
    }

    @Override
    public UpdateAppIdea setKey(java.lang.String key) {
      return (UpdateAppIdea) super.setKey(key);
    }

    @Override
    public UpdateAppIdea setOauthToken(java.lang.String oauthToken) {
      return (UpdateAppIdea) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateAppIdea setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateAppIdea) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateAppIdea setQuotaUser(java.lang.String quotaUser) {
      return (UpdateAppIdea) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateAppIdea setUserIp(java.lang.String userIp) {
      return (UpdateAppIdea) super.setUserIp(userIp);
    }

    @Override
    public UpdateAppIdea set(String parameterName, Object value) {
      return (UpdateAppIdea) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Appideaendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Appideaendpoint}. */
    @Override
    public Appideaendpoint build() {
      return new Appideaendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AppideaendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAppideaendpointRequestInitializer(
        AppideaendpointRequestInitializer appideaendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(appideaendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
