/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-02-27 at 04:01:33 UTC 
 * Modify at your own risk.
 */

package com.appsack.model.appideaendpoint.model;

/**
 * Model definition for AppIdea.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the appideaendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppIdea extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long categoryId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String details;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer numVotes;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String summary;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long timeEdited;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long timeSubmitted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getCategoryId() {
    return categoryId;
  }

  /**
   * @param categoryId categoryId or {@code null} for none
   */
  public AppIdea setCategoryId(java.lang.Long categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDetails() {
    return details;
  }

  /**
   * @param details details or {@code null} for none
   */
  public AppIdea setDetails(java.lang.String details) {
    this.details = details;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public AppIdea setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getNumVotes() {
    return numVotes;
  }

  /**
   * @param numVotes numVotes or {@code null} for none
   */
  public AppIdea setNumVotes(java.lang.Integer numVotes) {
    this.numVotes = numVotes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSummary() {
    return summary;
  }

  /**
   * @param summary summary or {@code null} for none
   */
  public AppIdea setSummary(java.lang.String summary) {
    this.summary = summary;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTimeEdited() {
    return timeEdited;
  }

  /**
   * @param timeEdited timeEdited or {@code null} for none
   */
  public AppIdea setTimeEdited(java.lang.Long timeEdited) {
    this.timeEdited = timeEdited;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTimeSubmitted() {
    return timeSubmitted;
  }

  /**
   * @param timeSubmitted timeSubmitted or {@code null} for none
   */
  public AppIdea setTimeSubmitted(java.lang.Long timeSubmitted) {
    this.timeSubmitted = timeSubmitted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public AppIdea setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public AppIdea setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public AppIdea set(String fieldName, Object value) {
    return (AppIdea) super.set(fieldName, value);
  }

  @Override
  public AppIdea clone() {
    return (AppIdea) super.clone();
  }

}
