/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-02-27 at 04:02:03 UTC 
 * Modify at your own risk.
 */

package com.appsack.model.userchangelogendpoint.model;

/**
 * Model definition for UserChangeLog.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the userchangelogendpoint. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UserChangeLog extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime dateChanged;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fieldChanged;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String valueBeforeChange;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDateChanged() {
    return dateChanged;
  }

  /**
   * @param dateChanged dateChanged or {@code null} for none
   */
  public UserChangeLog setDateChanged(com.google.api.client.util.DateTime dateChanged) {
    this.dateChanged = dateChanged;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFieldChanged() {
    return fieldChanged;
  }

  /**
   * @param fieldChanged fieldChanged or {@code null} for none
   */
  public UserChangeLog setFieldChanged(java.lang.String fieldChanged) {
    this.fieldChanged = fieldChanged;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public UserChangeLog setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public UserChangeLog setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getValueBeforeChange() {
    return valueBeforeChange;
  }

  /**
   * @param valueBeforeChange valueBeforeChange or {@code null} for none
   */
  public UserChangeLog setValueBeforeChange(java.lang.String valueBeforeChange) {
    this.valueBeforeChange = valueBeforeChange;
    return this;
  }

  @Override
  public UserChangeLog set(String fieldName, Object value) {
    return (UserChangeLog) super.set(fieldName, value);
  }

  @Override
  public UserChangeLog clone() {
    return (UserChangeLog) super.clone();
  }

}
