/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-02-27 at 04:01:50 UTC 
 * Modify at your own risk.
 */

package com.appsack.model.categoryendpoint.model;

/**
 * Model definition for Category.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the categoryendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Category extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String androidCategoryName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String iOSCategoryName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAndroidCategoryName() {
    return androidCategoryName;
  }

  /**
   * @param androidCategoryName androidCategoryName or {@code null} for none
   */
  public Category setAndroidCategoryName(java.lang.String androidCategoryName) {
    this.androidCategoryName = androidCategoryName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIOSCategoryName() {
    return iOSCategoryName;
  }

  /**
   * @param iOSCategoryName iOSCategoryName or {@code null} for none
   */
  public Category setIOSCategoryName(java.lang.String iOSCategoryName) {
    this.iOSCategoryName = iOSCategoryName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public Category setKey(Key key) {
    this.key = key;
    return this;
  }

  @Override
  public Category set(String fieldName, Object value) {
    return (Category) super.set(fieldName, value);
  }

  @Override
  public Category clone() {
    return (Category) super.clone();
  }

}
