/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-02-14 18:40:25 UTC)
 * on 2014-02-27 at 04:01:29 UTC 
 * Modify at your own risk.
 */

package com.appsack.model.appideavoteendpoint.model;

/**
 * Model definition for AppIdeaVote.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the appideavoteendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppIdeaVote extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long appIdeaId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer vote;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getAppIdeaId() {
    return appIdeaId;
  }

  /**
   * @param appIdeaId appIdeaId or {@code null} for none
   */
  public AppIdeaVote setAppIdeaId(java.lang.Long appIdeaId) {
    this.appIdeaId = appIdeaId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public AppIdeaVote setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public AppIdeaVote setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getVote() {
    return vote;
  }

  /**
   * @param vote vote or {@code null} for none
   */
  public AppIdeaVote setVote(java.lang.Integer vote) {
    this.vote = vote;
    return this;
  }

  @Override
  public AppIdeaVote set(String fieldName, Object value) {
    return (AppIdeaVote) super.set(fieldName, value);
  }

  @Override
  public AppIdeaVote clone() {
    return (AppIdeaVote) super.clone();
  }

}
